"""
Centralized configuration loaded from environment variables (via .env).

Provides two DB connection dicts (a full-privilege one for writes/migrations
and a read-only one for user-facing SQL generated by the LLM) plus a
SQLAlchemy-style connection URL used by langchain-postgres (PGVector).
"""

from dotenv import load_dotenv
import os

# Reads the .env file in the project root and injects its key=value pairs
# into os.environ, so os.getenv(...) below can find them.
load_dotenv()

# Full-access DB credentials, used for schema creation, data loading and
# vector-store writes.
DB_CONFIG = {
    "host": os.getenv("DB_HOST"),
    "port": os.getenv("DB_PORT"),
    "dbname": os.getenv("DB_NAME"),
    "user": os.getenv("DB_USER"),
    "password": os.getenv("DB_PASSWORD"),
}

# Read-only DB credentials, used when executing LLM-generated SQL
# (see services/text2sql.py) so a bad/malicious query can only ever SELECT,
# never mutate data — a defense-in-depth layer on top of is_safe_sql().
DB_READONLY_CONFIG = {
    "host": os.getenv("DB_HOST"),
    "port": os.getenv("DB_PORT"),
    "dbname": os.getenv("DB_NAME"),
    "user": os.getenv("DB_READONLY_USER"),
    "password": os.getenv("DB_PASSWORD"),
}
# connection = "postgresql+psycopg://user:password@host:port/dbname"

# SQLAlchemy-style connection string (used by langchain-postgres's PGVector
# store in services/ingest.py, which expects a URL rather than a dict).
DB_URL = f"postgresql+psycopg://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
